version: "2.2"
services:
    frontend:
      image: node:14.17-alpine
      command: sh -c "npm install && npm run dev"
      ports: 
        - 3000:3000
      working_dir: /hero-cards-game-UI
      volumes: 
        - ./:/hero-cards-game-UI
    server:
      image: hero-cards-game-server:1.3
      ports:
        - 8080:8080