version: "2.2"
services:
    frontend:
      image: node:14.17-alpine
      command: sh -c "npm install && npm run dev"
      ports: 
        - 3000:3000
      working_dir: /hero-cards-game-UI
      volumes: 
        - ./:/hero-cards-game-UI
        
    mysql_db:
        image: mysql:8.0
        restart: always
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: heroCardsGame
    
    server:
        image: tacs-card-games_server:latest
        restart: on-failure
        depends_on:
            - mysql_db
        ports:
            - 8080:8080
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: heroCardsGame
    
volumes:
    mysql-data: