version: "2.2"
services:
    frontend:
        image: fesposta/hero-cards-game-ui:1.5
        ports: 
            - 3000:5000

    mysql_db:
        image: mysql:8.0
        restart: always
        ports:
            - 3306:3306
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: heroCardsGame
    
    server:
        image: fesposta/hero-cards-game-server:1.5
        restart: on-failure
        depends_on:
            - mysql_db
        ports:
            - 8080:8080
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: heroCardsGame
    
volumes:
    mysql-data: