version: "2.2"
services:
    frontend:
        image: fesposta/hero-cards-game-ui:1.4
        ports: 
            - 3000:5000
    server:
        image: fesposta/hero-cards-game-server:1.4
        ports:
            - 8080:8080