version: "2.2"
services:
    frontend:
        image: fesposta/hero-cards-game-ui
        ports: 
            - 5000:5000
    server:
        image: fesposta/hero-cards-game-server:latest
        ports:
            - 8080:8080